### ISSUE TITLE
¿Podrías hacer un sistema de Clones en la HK?

### ISSUE THREAD

**Issue by lElectrico** [DenzelCode/MasterCMS#1]
He intentado hacerlo por mí mismo, pero al ser PDO no es mi especialidad y no es que me haya salido del todo bien xd

**Comment by DenzelCode** [comment]
Vale amigo, estaremos trabajando en esa update 3.1.2 👍

**Comment by DenzelCode** [comment]
Update subida, disfruta de la caracteristica!

**Comment by alair069** [comment]
@DenzelCode Do you have twitter or email?
